### ISSUE TITLE
Error trying to save and exit

### ISSUE THREAD

**Issue by killerzoreo** [thisis2838/SourceSplit#5]
Encountered one or more problems while writing to log file. Logging will be disabled for this session of SourceSplit!

------EXCEPTIONS------

[0] System.IO.IOException
    Message: The process cannot access the file 'C:\Users\Tim\Downloads\LiveSplit_1.7.6\sourcesplit_log.txt' because it is being used by another process.
    Source: mscorlib
    Stacktrace: 
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

           at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)

           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)

           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)

           at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)

           at LiveSplit.SourceSplit.Utilities.Logging.WriteToFile(Message msg)

**Comment by thekovic** [comment]
Same
```
Encountered one or more problems while writing to log file. Logging will be disabled for this session of SourceSplit.

------EXCEPTIONS------

[0] System.IO.IOException
    Message: The process cannot access the file 'C:\LiveSplit\SourceSplit\logs\2025-08-18.csv' because it is being used by another process.
    Source: mscorlib
    Stacktrace: 
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

           at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)

           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)

           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)

           at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)

           at LiveSplit.SourceSplit.Utilities.Logging.WriteToFile(Message msg)


```
