### ISSUE TITLE
unable to load dll "coredll.dll"

### ISSUE THREAD

**Issue by p1k0chu** [thisis2838/SourceSplit#7]
Error message:
```
Encountered unhandled exception when reading game memory

------EXCEPTIONS------

[0] System.DllNotFoundException
    Message: Unable to load DLL 'coredll.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    Source: LiveSplit.SourceSplit
    Stacktrace: 
           at LiveSplit.SourceSplit.Utilities.WinUtils.GetModuleFileNameEx(IntPtr hProcess, IntPtr hModule, StringBuilder lpFilename, Int32 nSize)

           at LiveSplit.SourceSplit.Utilities.ProcUtils.ModulesWow64SafeNoCache(Process p)

           at LiveSplit.SourceSplit.GameHandling.GameMemory.<>c__DisplayClass84_0.<TryGetGameProcess>b__2(Process p)

           at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)

           at LiveSplit.SourceSplit.GameHandling.GameMemory.TryGetGameProcess(GameState& state_)

           at LiveSplit.SourceSplit.GameHandling.GameMemory.MemoryReadThread(CancellationTokenSource cts)


```
This error occurs whenever the game is running (Portal)

**Comment by p1k0chu** [comment]
I forgot to say that I use Surce Unpack

**Comment by kaktus313** [comment]
same problem with Ghosting

**Comment by VaPezizi** [comment]
Got the same message with steam version

**Comment by p1k0chu** [comment]
yesterday's hotfix fixed it
